# Generated by Django 5.0.7 on 2024-07-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_subs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
