# Generated by Django 5.0.7 on 2024-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='subscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Vendedor', 'Vendedor'), ('Bodeguero', 'Bodeguero')], default='Cliente', max_length=20),
        ),
    ]
