# Generated by Django 5.0.7 on 2024-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_apellidos_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Carreras', 'Carreras'), ('Simulación', 'Simulación'), ('Acción', 'Acción'), ('Horror', 'Horror'), ('Aventura', 'Aventura'), ('Supervivencia', 'Supervivencia'), ('Sandbox', 'Sandbox'), ('Estrategia', 'Estrategia'), ('Party', 'Party'), ('Deportes', 'Deportes'), ('Rol', 'Rol')], max_length=100, null=True),
        ),
    ]
